---
title: "Empress_i"
author: "Author here"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

This is just an example. The data used below is openly accessible on [Empres-i](http://empres-i.fao.org/
empres-i)
Searched: 
```{r}
library(tidyverse)
library(lubridate)
library(leaflet)
library(sp)

EMP <- readLines("./Empress.csv")
EMP <- gsub("^\"|\"$", "", EMP)
EMP <- gsub("\"\"", "\"", EMP)

EMP2 <- read.csv(text = EMP, header=FALSE, stringsAsFactors = FALSE)
colnames(EMP2) <- as.character(EMP2[1,])
EMP2 <- EMP2[-1, -c(21:26)]
#head(EMP2)
#names(EMP2)
#levels(as.factor(EMP2$speciesDescription))

EMP2$reportingDate <- dmy(EMP2$reportingDate)


```

```{r}
asfmap <- EMP2

asfmap$reportingDate <- as.Date(asfmap$reportingDate, format = "%d/%m/%Y")
#asfmap <- subset(asfmap, reportingDate >= (Sys.Date() - 14)) 
#asfmap <- filter(asfmap, reportingDate >= "2019-01-01")
# fix points WE
# asfmap$longitude <- ifelse(asfmap$long == "WE", paste0("-", asfmap$long), asfmap$long)


asfdp_map <- filter(asfmap, speciesDescription == "domestic, swine" )
asfwb_map <- filter(asfmap, speciesDescription == "wild, wild boar" )


# convert to sp object and assign projection

coordinates(asfdp_map) <- cbind(as.numeric(asfdp_map$longitude), as.numeric(asfdp_map$latitude))
proj4string(asfdp_map)<- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")

coordinates(asfwb_map) <- cbind(as.numeric(asfwb_map$long), as.numeric(asfwb_map$lat))
proj4string(asfwb_map)<- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")


# popup
popup_wb <- paste("Datum:", asfwb_map@data$reportingDate)

popup_dp <- paste("Datum:", asfdp_map@data$reportingDate)


#plot map
m <- leaflet()
m <- addTiles(m, urlTemplate = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
m <- addCircleMarkers(m, data = asfwb_map, radius = 0.5, popup = popup_wb) 
m <- addCircleMarkers(m, data = asfdp_map, radius =  1, color = "#cb181d", fillOpacity = 1, popup = popup_dp)
                      #fillOpacity = 0.5, popup = popup_mid)
#m <- addCircleMarkers(m, data = asfdp_small, radius = 1 , color = "#ef3b2c", fillColor = "#ef3b2c",
                      #fillOpacity = 0.5, popup = popup_small)
#m <- addCircleMarkers(m, data = asfdp_mid, radius = 2 , color = "#cb181d", fillColor = "#cb181d",
                      #fillOpacity = 0.5, popup = popup_mid)
#m <- addCircleMarkers(m, data = asfdp_large, radius = 2 , color = "#67000d", fillColor = "#67000d",
                      #fillOpacity = 0.5, popup = popup_large)
m <- addScaleBar(m)
#saveWidget(m, file = "ASF_map_htm.html") 

m
```



Compare empress-i to adns
For the same period

```{r}

EMP3 <- readLines("./Empress2.csv")
EMP3 <- gsub("^\"|\"$", "", EMP3)
EMP3 <- gsub("\"\"", "\"", EMP3)

EMP4 <- read.csv(text = EMP3, header=FALSE, stringsAsFactors = FALSE)
colnames(EMP4) <- as.character(EMP4[1,])
EMP4 <- EMP4[-1, -c(21:26)]
head(EMP4)
names(EMP4)
levels(as.factor(EMP4$speciesDescription))

EMP4$observationDate <- dmy(EMP4$observationDate)

#EMP2 #empress 20180101-201807-31 reporting date
#EMP4 #empress 2018-01-01 - 2018-07-31 observations date
ADNS <- read.csv2("adns_comp.csv", header = TRUE) #ADNS confirmation date 20180101 - 2018-07-31
ADNS$Confirmation.date <- dmy(ADNS$Confirmation.date)
nrow(EMP2)
nrow(EMP4)
nrow(ADNS)

min(EMP2$reportingDate)
max(EMP2$reportingDate)

min(EMP4$observationDate)
max(EMP4$observationDate)

min(ADNS$Confirmation.date)
max(ADNS$Confirmation.date)

tally(group_by(EMP2, country, speciesDescription))
tally(group_by(EMP4, country, speciesDescription))
tally(group_by(ADNS, Country, Disease))

```


```{r}
EMP4$country <- as.factor(EMP4$country)

ggplot(EMP4, aes(floor_date(observationDate, "week"), fill = speciesDescription)) + 
  geom_bar(position = "dodge")

ggplot(EMP2, aes(floor_date(reportingDate, "week"), fill = country)) + 
  geom_bar()

ggplot(EMP2, aes(reportingDate, fill = country)) + 
  geom_bar()
```

